#!/bin/bash
set -e

# Get rid of existing binary
rm -f libcompose-cli

go generate

# Build binaries
go build \
   -ldflags="-w -X github.com/docker/libcompose/version.GITCOMMIT=`git rev-parse --short HEAD`" \
   -o bundles/libcompose-cli \
   ./cli/main.go
