#!/bin/bash

export SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export DEST=.

bundle .integration-daemon-start

TESTFLAGS="$TESTFLAGS -test.timeout=30m -check.v"

cd integration
TESTVERBOSE=$TESTVERBOSE go test $TESTFLAGS
cd ..

bundle .integration-daemon-stop
